age=20
height=6.0
complex_num=2+4j
name="rahul"
fruits=["apple","banana","mango"]
colors=("red","green","blue")
numbers={1,2,3,4}
student={"name":"rahul","age":30}
is_student=True
value=None
print(age,type(age))
print(height,type(height))
print(complex_num,type(complex_num))
print(name,type(name))
print(fruits,type(fruits))
print(colors,type(colors))
print(numbers,type(numbers))
print(student,type(student))
print(is_student,type(is_student))
print(value,type(value))

